### ISSUE TITLE
Example extension method not compiling in the docs of Diagnostic Warning - Disposable Transient Components

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [simpleinjector/Documentation#110]
Page: [Diagnostic Warning - Disposable Transient Components](https://simpleinjector.readthedocs.io/en/latest/disposabletransientcomponent.html)

The suggested extension method:
```C#
public static void RegisterDisposableTransient<TService, TImplementation>(
    this Container c)
    where TImplementation: class, IDisposable, TService
    where TService : class
{
    var scoped = Lifestyle.Scoped;
    var r = Lifestyle.Transient.CreateRegistration<TService, TImplementation>(c);
    r.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "ignore");
    c.AddRegistration(typeof(TService), r);
    c.RegisterInitializer<TImplementation>(o => scoped.RegisterForDisposal(c, o));
}
```

Does not compile with SimpleInjector 4.9.0, raising compilation errors:
- Lifestyle.CreateRegistration<TService, TImplementation>(Container)' is obsolete: Please use CreateRegistration<TConcrete>(Container) instead. Will be removed in version 5.0
- 'Lifestyle' does not contain a definition for 'RegisterForDisposal' and no accessible extension method 'RegisterForDisposal' accepting a first argument of type 'Lifestyle' could be found (are you missing a using directive or an assembly reference?)

Should it be fixed somehow?

**Comment by gabriele-ricci-kyklos** [comment]
This is a _compiling_ version, untested because I realized this is not my case:
```C#
public static void RegisterDisposableTransient<TService, TImplementation>(this Container c)
    where TImplementation : class, IDisposable, TService
    where TService : class
{
    ScopedLifestyle scoped = Lifestyle.Scoped;
    Registration r = Lifestyle.Transient.CreateRegistration<TImplementation>(c);
    r.SuppressDiagnosticWarning(DiagnosticType.DisposableTransientComponent, "ignore");
    c.AddRegistration(typeof(TService), r);
    c.RegisterInitializer<TImplementation>(o => scoped.RegisterForDisposal(c, o));
}
```

**Comment by dotnetjunkie** [comment]
Hi Gabriele,

The correct method to call is indeed `Lifestyle.CreateRegistration<TImplementation>()`, as you already thought. `CreateRegistration<TService, TImplementation>()` has been deprecated, because `TService` is never used (this was changed in v4.0).

I updated the documentation to reflect this.

Thank you for reporting this.
